# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  - group: s3PushInstallers
  - group: pipeline-tokens
  - name: configuration
    value: Release

pool: 'rhino-compute'

steps:
- task: NuGetToolInstaller@1

- task: NuGetAuthenticate@1
  inputs:
    forceReinstallCredentialProvider: true

- task: NuGetCommand@2
  displayName: 'Restoring NuGet packages'
  inputs:
      command: 'restore'
      restoreSolution: 'AdSecGH.sln'

- task: VSBuild@1
  displayName: 'Building project in $(configuration)'
  inputs:
    solution: 'AdSecGH.sln'
    msbuildArgs: '/p:AppxBundlePlatforms="x64" /p:AppxPackageDir="$(build.artifactStagingDirectory)\AppxPackages" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload /m /nr:false'
    platform: 'x64'
    configuration: '$(configuration)'
    clean: true
  env:
    MSBUILDDISABLENODEREUSE: 1

- powershell: |
    dotnet test --collect:"XPlat Code Coverage" /TestAdapterPath:$env:UserProfile\.nuget\packages\coverlet.collector\3.2.0\build --results-directory .\results .\AdSecGHTests\bin\x64\Release\net6.0\AdSecGHTests.dll
  displayName: dotnet tests

- task: PowerShell@2
  displayName: Check for existing tags
  inputs:
    targetType: 'inline'
    script: |
        $versionInfo = $(Get-Item .\AdSecGH\bin\x64\Release\AdSecGH.dll).VersionInfo
        echo $versionInfo
        $fullVersion = [array]${versionInfo}.FileVersion.split('.')
        $currentTime = $(Get-Date -Format "dddd MM/dd/yyyy HH:mm")
        $majorVersion = [string]$fullVersion[0]
        $minorVersion = [string]$fullVersion[1]
        $spVersion = [string]$fullVersion[2]
        $buildNumber = [string]$fullVersion[3]

        $tag = [array]@($exeName,$majorVersion,$minorVersion,$spVersion,$buildNumber)
        $tagNumbersOnly = [array]@($majorVersion,$minorVersion,$spVersion,$buildNumber)

        $dotSeparatedTag = $majorVersion + "." + $minorVersion + "." + $spVersion + "-beta"
        $underscoreSeparatedTag = $majorVersion + "_" + $minorVersion + "_" + $spVersion + "_" + $buildNumber
        $tagNumbersOnlyUnderscore = $majorVersion + "_" + $minorVersion + "_" + $spVersion + "_" + $buildNumber
        $tagNumbersOnlydot = $majorVersion + "." + $minorVersion + "." + $spVersion + "." + $buildNumber
        
        Write-Host ("##vso[task.setvariable variable=dotSeparatedTag]$dotSeparatedTag")
        git rev-parse $dotSeparatedTag
        if($lastExitCode -eq 0){Write-Host ("##vso[task.setvariable variable=TAG_EXISTS]true")}
        if($lastExitCode -eq 0){
          $tagExists = 'true'
          echo $tagExists
        }
    errorActionPreference: 'continue'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    ignoreLASTEXITCODE: true

- powershell: |
    cd AdSecGH\bin\x64
    curl https://files.mcneel.com/yak/tools/latest/yak.exe -o yak.exe
    .\yak version
    cd Release
    ..\yak spec
    Add-Content manifest.yml 'icon: AdSecIcon.png'
    ..\yak build --platform win
    $yakCurrentVersName = Get-ChildItem -Path . -Filter "*.yak"
    $yakRh7Name =  $yakCurrentVersName -Replace "rh6_27", "rh7_0"
    Rename-Item -Path $yakCurrentVersName -NewName $yakRh7Name
    ..\yak build --platform win
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), ne(variables.TAG_EXISTS, 'true'))
  displayName: Package yak

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'AdSecGH/*.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'dotSeparatedTag'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), ne(variables.TAG_EXISTS, 'true'))
  displayName: Package NuGet

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_peterjgrainger'
    repositoryName: 'arup-group/AdSec-Grasshopper'
    action: 'edit'
    target: '$(Build.SourceVersion)'
    tag: '$(dotSeparatedTag)'
    title: 'AdSecGH version $(dotSeparatedTag)'
    releaseNotesSource: 'inline'
    releaseNotesInline: |
      Created from commit https://github.com/arup-group/AdSec-Grasshopper/commit/$(Build.SourceVersion)
    assets: |
      $(System.DefaultWorkingDirectory)/**/*.yak
      $(Build.ArtifactStagingDirectory)/**/*.nupkg
      $(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg
    assetUploadMode: 'replace'
    isDraft: true
    isPreRelease: true
    addChangeLog: false
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), ne(variables.TAG_EXISTS, 'true'))
  displayName: 'Publishing assets to Github'
