#codecov:
#    notify:
#        after_n_builds: 2
#flags:
#  adsecgh:
#    carryforward: false
#  integration:
#    carryforward: false
ignore:
  - "AdSecGHTests"  # ignore folders and all its contents